### ISSUE TITLE
Flaky MacOS test suite

### ISSUE THREAD

**Issue by iansan5653** [github/combobox-nav#58]
The CI test suite intermittently fails on MacOS due to what looks like a race condition:

```
npm ERR! code 1
npm ERR! path /Users/runner/work/combobox-nav/combobox-nav/node_modules/chromium
npm ERR! command failed
npm ERR! command sh -c node install.js
npm ERR! Step 1. Retrieving Chromium revision number
npm ERR! Step 2. Downloading Chromium revision 1025666
npm ERR! /Users/runner/work/combobox-nav/combobox-nav/node_modules/p-cancelable/index.js:48
npm ERR! 					throw new Error('The `onCancel` handler was attached after the promise settled.');
npm ERR! 					      ^
npm ERR! 
npm ERR! Error: The `onCancel` handler was attached after the promise settled.
npm ERR!     at onCancel (/Users/runner/work/combobox-nav/combobox-nav/node_modules/p-cancelable/index.js:48:12)
npm ERR!     at makeRequest (/Users/runner/work/combobox-nav/combobox-nav/node_modules/got/dist/source/as-promise/index.js:38:13)
npm ERR!     at Request.<anonymous> (/Users/runner/work/combobox-nav/combobox-nav/node_modules/got/dist/source/as-promise/index.js:143:17)
npm ERR!     at Object.onceWrapper (node:events:642:26)
npm ERR!     at Request.emit (node:events:527:28)
npm ERR!     at Timeout.retry (/Users/runner/work/combobox-nav/combobox-nav/node_modules/got/dist/source/core/index.js:1278:30)
npm ERR!     at listOnTimeout (node:internal/timers:55[9](https://github.com/github/combobox-nav/runs/7410232560?check_suite_focus=true#step:4:10):17)
npm ERR!     at processTimers (node:internal/timers:502:7)
npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/runner/.npm/_logs/2022-07-19T[13](https://github.com/github/combobox-nav/runs/7410232560?check_suite_focus=true#step:4:14)_32_24_7[14](https://github.com/github/combobox-nav/runs/7410232560?check_suite_focus=true#step:4:15)Z-debug-0.log
```

This doesn't happen on Ubuntu/Windows.

**Comment by iansan5653** [comment]
As an example, [this run](https://github.com/github/combobox-nav/runs/7410779706?check_suite_focus=true) failed 3 times before passing:

<img width="329" alt="Screenshot of the test suite results. There are three failures followed by one successful run." src="https://user-images.githubusercontent.com/2294248/179769656-11c69caa-f86d-41cf-b1a5-9e31406cac44.png">
